# Generated by Django 5.1.1 on 2024-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='complemento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
