# Generated by Django 5.1.1 on 2024-10-08 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
    ]
