# Generated by Django 5.1.1 on 2024-10-12 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_testimony_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='way_payment',
            field=models.CharField(choices=[('cartão credito', 'Cartão credito'), ('cartão debito', 'Cartão debito'), ('a vista', 'A vista')], max_length=50),
        ),
    ]
