# Generated by Django 5.1.1 on 2024-10-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_scheduling_collaborator_alter_scheduling_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='addess',
            new_name='address',
        ),
    ]
