# Generated by Django 5.1.1 on 2024-10-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_addess_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('pendente', 'Pendente')], default='pendente', max_length=12),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('pendente', 'Pendente')], default='pendente', max_length=12),
        ),
    ]
