# Generated by Django 5.1.1 on 2024-10-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimony_status_alter_scheduling_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
