# Generated by Django 5.1.1 on 2024-10-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_faq_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
