# Generated by Django 5.1.1 on 2024-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimony',
            name='date',
        ),
        migrations.AddField(
            model_name='testimony',
            name='score',
            field=models.IntegerField(default=4),
        ),
    ]
