# Generated by Django 5.1.1 on 2024-10-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_testimony_date_testimony_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='score',
            field=models.IntegerField(),
        ),
    ]
