# Generated by Django 5.1.1 on 2024-10-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_testimony_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=50)),
                ('salary', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='media/service/'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('curriculum_vitae', models.FileField(null=True, upload_to='media/curriculum_vitae/')),
                ('mesage', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobopening')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('jobopening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobopening')),
            ],
        ),
    ]
