# Generated by Django 5.1.1 on 2024-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_jobopening_alter_service_image_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='media/curriculum_vitae/'),
        ),
    ]
