# Generated by Django 5.1.1 on 2024-10-19 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_candidate_curriculum_vitae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('carro', 'Carro'), ('ônibus', 'Ônibus'), ('moto', 'Moto')], max_length=7)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_for', models.CharField(choices=[('empresa', 'Empresa'), ('colaborador', 'Colaborador'), ('cliente', 'Cliente')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='99', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='road',
            field=models.CharField(default='st', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='hour_spent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='registration_date',
            field=models.DateTimeField(default='2024-10-08'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='status',
            field=models.CharField(choices=[('em andamento', 'Em andamento'), ('reprovado', 'Reprovado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('pendente', 'Pendente')], default='pendente', max_length=12),
        ),
        migrations.CreateModel(
            name='CanceledAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheduling')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.collaborator'),
        ),
        migrations.CreateModel(
            name='CompletedSerive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('customer_satisfation', models.CharField(choices=[('satisfeito', 'Satisfeito'), ('muito satisfeito', 'Muito satisfeito'), ('insatisfeito', 'insatisfeito'), ('muito insatisfeito', 'Muito insatisfeito')], max_length=50)),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheduling')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('não pago', 'Não pago')], max_length=50)),
                ('payment_date', models.DateField()),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scheduling')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_cep', models.CharField(max_length=10)),
                ('max_cep', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('estate', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collaborator')),
            ],
        ),
        migrations.AddField(
            model_name='scheduling',
            name='outbound_transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outbound_transport', to='core.transport'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='return_transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_transport', to='core.transport'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
