# Generated by Django 5.1.1 on 2024-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transport_client_phone_client_road_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='road',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
