# Generated by Django 5.1.1 on 2024-10-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_client_phone_alter_client_road_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.client'),
        ),
    ]
