# Generated by Django 5.1.1 on 2024-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_client_road'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='capa',
            field=models.FileField(default='', upload_to='media/testimony/'),
        ),
    ]
