# Generated by Django 5.1.1 on 2024-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_testimony_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
