# Generated by Django 5.1.1 on 2024-10-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_generalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
