# Generated by Django 5.1.1 on 2024-10-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_generalinformation_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='aboutus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='clients',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='professional',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='yearexpirence',
            field=models.IntegerField(null=True),
        ),
    ]
