# Generated by Django 5.1.1 on 2024-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_generalinformation_aboutus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='projects',
            new_name='affiliatedsocieties',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='affiliated',
            field=models.IntegerField(null=True),
        ),
    ]
